# Search settings
[search]
query_type = "Top"  # "Latest" or "Top"
max_pages = 5  # Maximum pages to fetch per query
parallel_requests = 10
max_tweets = 100
fetch_interactions = false
max_markets = 5

[look_back]
year = 2026
month = 1
days = 30

[fetch_limits]
max_replies = 100
max_quotes = 100
max_retweeters = 100

[categories]
crypto = [
    "@intocryptoverse",
    "@CryptoCred",
    "@CryptoCapo_",
    "@ColdBloodShill",
    "@CryptoMichNL",
    "@IamCryptoWolf",
    "@AltcoinPsycho",
    "@CryptoJelleNL",
    "@TheCryptoLark",
    "@CryptoKaleo",
    "@I_Am_The_ICT"
]

politics = [
    "@NateSilver538",
    "@EWErickson",
    "@BillKristol",
    "@NathanJRobinson",
    "@mattyglesias",
    "@KyleKulinski",
    "@TuckerCarlson",
    "@AnaKasparian",
    "@SteveSchmidtSES",
    "@benshapiro"
]

sports = [
    "@SharpFootball",
    "@ToddFuhrman",
    "@BenjaminSolak",
    "@FezzikSports",
    "@betfirmsjack",
    "@KyleHunterPicks",
    "@PatMcAfeeShow",
    "@BillSimmons"
]

finance = [
    "@CathieDWood",
    "@EconguyRosie",
    "@PeterLBrandt",
    "@lisaabramowicz1",
    "@NickTimiraos",
    "@TruthGundlach",
    "@LizAnnSonders",
    "@elerianm",
    "@AswathDamodaran",
]

[trust_weights]
# Trust weights for different interaction types
follow = 30
mention = 30
reply = 20
retweet = 50
quote = 40
